on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: test Cairo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract scarb version
        run: |
          SCARB_VERSION=$(grep 'scarb-version = ' Scarb.toml | sed 's/scarb-version = "\(.*\)"/\1/')
          echo "SCARB_VERSION=$SCARB_VERSION" >> "$GITHUB_ENV"

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}

      - name: Extract foundry version
        run: |
          FOUNDRY_VERSION=$(grep 'snforge_std = ' Scarb.toml | sed 's/snforge_std = "\(.*\)"/\1/')
          echo "FOUNDRY_VERSION=$FOUNDRY_VERSION" >> "$GITHUB_ENV"

      - uses: foundry-rs/setup-snfoundry@v4
        with:
          starknet-foundry-version: ${{ env.FOUNDRY_VERSION }}

      - name: Install cairo-coverage
        run: curl -L https://raw.githubusercontent.com/software-mansion/cairo-coverage/main/scripts/install.sh | sh

      - name: Cairo lint
        run: scarb fmt --check --workspace

      - name: Run tests
        run: snforge test
